contig:
 TIG01: "SUPER_1"
 TIG02: "SUPER_2"
 TIG03: "SUPER_3"
 TIG04: "SUPER_4"
 TIG05: "SUPER_5"
 TIG06: "SUPER_6"
 TIG07: "SUPER_7"
 TIGW: "SUPER_W"
 TIGW1: "SUPER_W_unloc_1"
 TIGW2: "SUPER_W_unloc_2"
 TIGW3: "SUPER_W_unloc_3"
 TIGW4: "SUPER_W_unloc_4"
 TIGW5: "SUPER_W_unloc_5"
 TIGW6: "SUPER_W_unloc_6"
 TIGW7: "SUPER_W_unloc_7"
 TIGW8: "SUPER_W_unloc_8"
 TIGZ: "SUPER_Z"
 TIGSC: "SCAFFOLD_28 -L SCAFFOLD_15 -L SCAFFOLD_23 -L SCAFFOLD_27 -L SCAFFOLD_21 -L SCAFFOLD_24 -L SCAFFOLD_26 -L SCAFFOLD_22 -L SCAFFOLD_20"
 TIGMT: "SCAFFOLD_1"
listgvcf: "gvcf/CAM070588.g.vcf.gz -V gvcf/CAM070589.g.vcf.gz -V gvcf/CAM070591.g.vcf.gz -V gvcf/CAM070629.g.vcf.gz -V gvcf/CAM070647.g.vcf.gz -V gvcf/CAM070649.g.vcf.gz -V gvcf/CAM070882.g.vcf.gz -V gvcf/CAM070883.g.vcf.gz -V gvcf/CAM070884.g.vcf.gz -V gvcf/CAM070885.g.vcf.gz -V gvcf/CAM070886.g.vcf.gz -V gvcf/CAM070887.g.vcf.gz -V gvcf/CAM070913.g.vcf.gz -V gvcf/CAM070914.g.vcf.gz -V gvcf/CAM070915.g.vcf.gz -V gvcf/CAM070916.g.vcf.gz -V gvcf/05-555.g.vcf.gz -V gvcf/05-556.g.vcf.gz -V gvcf/05-559.g.vcf.gz -V gvcf/LdeS11-2379.g.vcf.gz -V gvcf/mm17-045.g.vcf.gz -V gvcf/mm17-046.g.vcf.gz -V gvcf/05-462.g.vcf.gz -V gvcf/05-463.g.vcf.gz -V gvcf/05-563.g.vcf.gz -V gvcf/02-2108.g.vcf.gz -V gvcf/09-146.g.vcf.gz -V gvcf/LdeS11-678.g.vcf.gz -V gvcf/LdeS11-1707.g.vcf.gz -V gvcf/LdeS11-734.g.vcf.gz -V gvcf/LdeS11-1960.g.vcf.gz -V gvcf/LdeS11-1961.g.vcf.gz -V gvcf/LdeS11-1962.g.vcf.gz -V gvcf/LdeS11-1972.g.vcf.gz -V gvcf/LdeS11-1973.g.vcf.gz -V gvcf/LdeS11-2243.g.vcf.gz -V gvcf/LdeS11-730.g.vcf.gz -V gvcf/LdeS11-731.g.vcf.gz"
