ID:
 CAM070588: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Ecuador_samples/Brevioleria/analysis/CAM070588.cram"
 CAM070589: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Ecuador_samples/Brevioleria/analysis/CAM070589.cram"
 CAM070591: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Ecuador_samples/Brevioleria/analysis/CAM070591.cram"
 CAM070629: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Ecuador_samples/Brevioleria/analysis/CAM070629.cram"
 CAM070647: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Ecuador_samples/Brevioleria/analysis/CAM070647.cram"
 CAM070649: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Ecuador_samples/Brevioleria/analysis/CAM070649.cram"
 CAM070882: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Ecuador_samples/Brevioleria/analysis/CAM070882.cram"
 CAM070883: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Ecuador_samples/Brevioleria/analysis/CAM070883.cram"
 CAM070884: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Ecuador_samples/Brevioleria/analysis/CAM070884.cram"
 CAM070885: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Ecuador_samples/Brevioleria/analysis/CAM070885.cram"
 CAM070886: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Ecuador_samples/Brevioleria/analysis/CAM070886.cram"
 CAM070887: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Ecuador_samples/Brevioleria/analysis/CAM070887.cram"
 CAM070913: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Ecuador_samples/Brevioleria/analysis/CAM070913.cram"
 CAM070914: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Ecuador_samples/Brevioleria/analysis/CAM070914.cram"
 CAM070915: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Ecuador_samples/Brevioleria/analysis/CAM070915.cram"
 CAM070916: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Ecuador_samples/Brevioleria/analysis/CAM070916.cram"
