forward:
 05-555: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/05-555_R1_001.fastq.gz"
 05-556: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/05-556_R1_001.fastq.gz"
 05-559: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/05-559_R1_001.fastq.gz"
 LdeS11-2379: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-2379_R1_001.fastq.gz"
 mm17-045: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/mm17-045_R1_001.fastq.gz"
 mm17-046: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/mm17-046_R1_001.fastq.gz"
 05-462: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/05-462_R1_001.fastq.gz"
 05-463: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/05-463_R1_001.fastq.gz"
 05-563: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/05-563_R1_001.fastq.gz"
 02-2108: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/02-2108_R1_001.fastq.gz"
 09-146: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/09-146_R1_001.fastq.gz"
 LdeS11-678: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-678_R1_001.fastq.gz"
 LdeS11-1707: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-1707_R1_001.fastq.gz"
 LdeS11-734: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-734_R1_001.fastq.gz"
 LdeS11-1960: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-1960_R1_001.fastq.gz"
 LdeS11-1961: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-1961_R1_001.fastq.gz"
 LdeS11-1962: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-1962_R1_001.fastq.gz"
 LdeS11-1972: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-1972_R1_001.fastq.gz"
 LdeS11-1973: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-1973_R1_001.fastq.gz"
 LdeS11-2243: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-2243_R1_001.fastq.gz"
 LdeS11-730: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-730_R1_001.fastq.gz"
 LdeS11-731: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-731_R1_001.fastq.gz"

reverse:
 05-555: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/05-555_R2_001.fastq.gz"
 05-556: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/05-556_R2_001.fastq.gz"
 05-559: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/05-559_R2_001.fastq.gz"
 LdeS11-2379: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-2379_R2_001.fastq.gz"
 mm17-045: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/mm17-045_R2_001.fastq.gz"
 mm17-046: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/mm17-046_R2_001.fastq.gz"
 05-462: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/05-462_R2_001.fastq.gz"
 05-463: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/05-463_R2_001.fastq.gz"
 05-563: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/05-563_R2_001.fastq.gz"
 02-2108: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/02-2108_R2_001.fastq.gz"
 09-146: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/09-146_R2_001.fastq.gz"
 LdeS11-678: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-678_R2_001.fastq.gz"
 LdeS11-1707: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-1707_R2_001.fastq.gz"
 LdeS11-734: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-734_R2_001.fastq.gz"
 LdeS11-1960: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-1960_R2_001.fastq.gz"
 LdeS11-1961: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-1961_R2_001.fastq.gz"
 LdeS11-1962: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-1962_R2_001.fastq.gz"
 LdeS11-1972: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-1972_R2_001.fastq.gz"
 LdeS11-1973: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-1973_R2_001.fastq.gz"
 LdeS11-2243: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-2243_R2_001.fastq.gz"
 LdeS11-730: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-730_R2_001.fastq.gz"
 LdeS11-731: "/lustre/scratch125/tol/teams/meier/analysis/sing_wei/Brevioleria/analysis/LdeS11-731_R2_001.fastq.gz"
